// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Clockwerkz.Domain.Entities
{
    [Table("CALENDARS", Schema = "Quartz")]
    public partial class Calendar
    {
        [Key]
        [Column("SCHED_NAME")]
        [StringLength(120)]
        public string SchedName { get; set; }
        [Key]
        [Column("CALENDAR_NAME")]
        [StringLength(200)]
        public string CalendarName { get; set; }
        [Required]
        [Column("CALENDAR")]
        public byte[] Calendar1 { get; set; }
    }
}