// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Clockwerkz.Domain.Entities
{
    [Table("LOCKS", Schema = "Quartz")]
    public partial class Lock
    {
        [Key]
        [Column("SCHED_NAME")]
        [StringLength(120)]
        public string SchedName { get; set; }
        [Key]
        [Column("LOCK_NAME")]
        [StringLength(40)]
        public string LockName { get; set; }
    }
}