// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Clockwerkz.Domain.Entities
{
    [Table("SCHEDULER_STATE", Schema = "Quartz")]
    public partial class SchedulerState
    {
        [Key]
        [Column("SCHED_NAME")]
        [StringLength(120)]
        public string SchedName { get; set; }

        [Key]
        [Column("INSTANCE_NAME")]
        [StringLength(200)]
        public string InstanceName { get; set; }

        [Column("LAST_CHECKIN_TIME")]
        public long LastCheckinTime { get; set; }

        [Column("CHECKIN_INTERVAL")]
        public long CheckinInterval { get; set; }
    }
}