// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Clockwerkz.Domain.Entities
{
    [Table("SIMPLE_TRIGGERS", Schema = "Quartz")]
    public partial class SimpleTrigger
    {
        [Key]
        [Column("SCHED_NAME")]
        [StringLength(120)]
        public string SchedName { get; set; }
        [Key]
        [Column("TRIGGER_NAME")]
        [StringLength(150)]
        public string TriggerName { get; set; }
        [Key]
        [Column("TRIGGER_GROUP")]
        [StringLength(150)]
        public string TriggerGroup { get; set; }
        [Column("REPEAT_COUNT")]
        public int RepeatCount { get; set; }
        [Column("REPEAT_INTERVAL")]
        public long RepeatInterval { get; set; }
        [Column("TIMES_TRIGGERED")]
        public int TimesTriggered { get; set; }

        [ForeignKey("SchedName,TriggerName,TriggerGroup")]
        [InverseProperty("SimpleTrigger")]
        public virtual Trigger Trigger { get; set; }
    }
}