// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Clockwerkz.Domain.Entities
{
    [Table("TRIGGERS", Schema = "Quartz")]
    public partial class Trigger
    {
        [Key]
        [Column("SCHED_NAME")]
        [StringLength(120)]
        public string SchedName { get; set; }
        [Key]
        [Column("TRIGGER_NAME")]
        [StringLength(150)]
        public string TriggerName { get; set; }
        [Key]
        [Column("TRIGGER_GROUP")]
        [StringLength(150)]
        public string TriggerGroup { get; set; }
        [Required]
        [Column("JOB_NAME")]
        [StringLength(150)]
        public string JobName { get; set; }
        [Required]
        [Column("JOB_GROUP")]
        [StringLength(150)]
        public string JobGroup { get; set; }
        [Column("DESCRIPTION")]
        [StringLength(250)]
        public string Description { get; set; }
        [Column("NEXT_FIRE_TIME")]
        public long? NextFireTime { get; set; }
        [Column("PREV_FIRE_TIME")]
        public long? PrevFireTime { get; set; }
        [Column("PRIORITY")]
        public int? Priority { get; set; }
        [Required]
        [Column("TRIGGER_STATE")]
        [StringLength(16)]
        public string TriggerState { get; set; }
        [Required]
        [Column("TRIGGER_TYPE")]
        [StringLength(8)]
        public string TriggerType { get; set; }
        [Column("START_TIME")]
        public long StartTime { get; set; }
        [Column("END_TIME")]
        public long? EndTime { get; set; }
        [Column("CALENDAR_NAME")]
        [StringLength(200)]
        public string CalendarName { get; set; }
        [Column("MISFIRE_INSTR")]
        public int? MisfireInstr { get; set; }
        [Column("JOB_DATA")]
        public byte[] JobData { get; set; }

        [ForeignKey("SchedName,JobName,JobGroup")]
        [InverseProperty("Triggers")]
        public virtual JobDetail JobDetail { get; set; }
        [InverseProperty("Trigger")]
        public virtual CronTrigger CronTrigger { get; set; }
        [InverseProperty("Trigger")]
        public virtual SimpleTrigger SimpleTrigger { get; set; }
        [InverseProperty("Trigger")]
        public virtual SimpropTrigger SimpropTrigger { get; set; }
    }
}