// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Clockwerkz.Domain;
using Clockwerkz.Domain.Entities;
using Clockwerkz.Persistence.Mappings;
using Microsoft.EntityFrameworkCore;

namespace Clockwerkz.Persistence
{
    public partial class ClockwerkzDbContext : DbContext, IClockwerkzDbContext
    {
        public ClockwerkzDbContext(DbContextOptions<ClockwerkzDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<BlobTrigger> BlobTriggers { get; set; }
        public virtual DbSet<Calendar> Calendars { get; set; }
        public virtual DbSet<CronTrigger> CronTriggers { get; set; }
        public virtual DbSet<FiredTrigger> FiredTriggers { get; set; }
        public virtual DbSet<JobDetail> JobDetails { get; set; }
        public virtual DbSet<Lock> Locks { get; set; }
        public virtual DbSet<PausedTriggerGrp> PausedTriggerGrps { get; set; }
        public virtual DbSet<SchedulerState> SchedulerStates { get; set; }
        public virtual DbSet<SimpleTrigger> SimpleTriggers { get; set; }
        public virtual DbSet<SimpropTrigger> SimpropTriggers { get; set; }
        public virtual DbSet<Trigger> Triggers { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new BlobTriggerMap());
            modelBuilder.ApplyConfiguration(new CalendarMap());
            modelBuilder.ApplyConfiguration(new CronTriggerMap());
            modelBuilder.ApplyConfiguration(new FiredTriggerMap());
            modelBuilder.ApplyConfiguration(new JobDetailMap());
            modelBuilder.ApplyConfiguration(new LockMap());
            modelBuilder.ApplyConfiguration(new PausedTriggerGrpMap());
            modelBuilder.ApplyConfiguration(new SchedulerStateMap());
            modelBuilder.ApplyConfiguration(new SimpleTriggerMap());
            modelBuilder.ApplyConfiguration(new SimpropTriggerMap());
            modelBuilder.ApplyConfiguration(new TriggerMap());
        }
    }
}